### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by vijaytembugade**
Live preview : https://vijaytembugade.github.io/XenonUI-Component-Library/documenation/documentation.html
I have added cards and Buttons in documenation .

```Not worked on responsiveness yet```

Feel free to punch out spelling and grammatical mistakes.

### CODE REVIEW

**Review by msdeshmukh009 — APPROVED** [review]
Everything is looking good to me.

**Review by Amandeep-sinha — APPROVED** [review]
Looking great Vijay ! Good to go ahead.
Naming conventions are also awesome

**Review by saurabhchirde — APPROVED** [review]
Looks good to merge.

**Comment by vaibhav18matere** [comment]
Super clean UI, no such big errors except few spelling mistakes and grammatical errors :
just change these small errors
1. card with **dismiss** check spelling in card component.
2.  in same section check sub-heading - it should be **an icon**
3. in profile avatar - space between **img** and **tag**
4. text-only-card check spelling **without**
5. sized avatar spelling **four types** also check the sequence of xs, sm, md and lg in description

**Comment by vijaytembugade** [comment]
> Super clean UI, no such big errors except few spelling mistakes and grammatical errors : just change these small errors
> 
> 1. card with **dismiss** check spelling in card component.
> 2. in same section check sub-heading - it should be **an icon**
> 3. in profile avatar - space between **img** and **tag**
> 4. text-only-card check spelling **without**
> 5. sized avatar spelling **four types** also check the sequence of xs, sm, md and lg in description

Thanks @vaibhav18matere

**Pull request merged**
