### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by vijaytembugade**
- Added Responsiveness on documentation site
- Added Lists and Toast components.

Preview link: https://vijaytembugade.github.io/XenonUI-Component-Library/documenation/documentation.html

image
image
image

### CODE REVIEW

**Comment by jatinmore** [comment]
Looks good to me

**Review by techieshubham30 — APPROVED** [review]

**Review by Chakravarthi0 — APPROVED** [review]

**Review by preethasri — APPROVED** [review]
looks good

**Review by tanveertkd — APPROVED** [review]

**Comment by horsemaker** [comment]
image
There's a small glitch Vijay. As you can see the button is still showing show toast when I can see the toast. This happened after I clicked on the small X icon. I guess, you forgot to update the state of the button when someone clicks on the X icon. Could we also add it?

**Comment by vijaytembugade** [comment]
> image There's a small glitch Vijay. As you can see the button is still showing show toast when I can see the toast. This happened after I clicked on the small X icon. I guess, you forgot to update the state of the button when someone clicks on the X icon. Could we also add it?

Oh yes. you caught it. I will update the thing

**Pull request merged**
