### PR TITLE
Text utilities and lists

### PR DESCRIPTION
**Pull request by vijaytembugade**
Added text-utilities and Lists. 

### Live preview for text Utilities: 
https://vijaytembugade.github.io/XenonUI-Component-Library/Components/Text%20Utilities/text_utilities.html

### Live preview for Lists 
https://vijaytembugade.github.io/XenonUI-Component-Library/Components/Lists/list.html

Text Utilities : 
- H1 to H6
- Titles and subtitle
- Centered text
- small text
- Inline text styles

List:
- Normal List
- Notification-list

### CODE REVIEW

**Review by poornima-alugubelly — APPROVED** [review]
looks good Vijay!

**Review by horsemaker — APPROVED** [review]
looks clean vijay! good to go 👌

**Review by MarkVed17 — APPROVED** [review]
Looks good, Vijay!

**Comment by preethasri** [comment]
Neat and clean vijay

**Review by tanveertkd — COMMENTED** [review]
Looks good!

**Pull request merged**
