### PR TITLE
Avatar and Badges 

### PR DESCRIPTION
**Pull request by vijaytembugade**
Check here live Badges : https://vijaytembugade.github.io/XenonUI-Component-Library/Components/Badge/badge.html
Check here Avatar: https://vijaytembugade.github.io/XenonUI-Component-Library/Components/Avatar/avatar.html
Added Avatar and Badges 
Documentation things are not added yet.

### CODE REVIEW

**Comment by horsemaker** [comment]
Avatars 👍

Badge with Icon:
- Icon seems Large
- Icon could be shifted to the left as it doesn't align on the top-right corner of the icon.

**Review by horsemaker — COMMENTED** [review]
Reviewed! 👍

**Review by abhijeetekad — APPROVED** [review]
Looks great. you can merge this.

**Review by horsemaker — COMMENTED** [review]
Reviewed! 👍

**Pull request merged**
